# Generated by Django 4.2.4 on 2023-09-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_chooseus_remove_about_customers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Image2',
            field=models.FileField(blank=True, null=True, upload_to='files/images/About/photos/Image/%Y/%m/%d/'),
        ),
    ]
